//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string des { get; set; }
        public float hest { get; set; }
        public Nullable<float> hreales { get; set; }
        public Nullable<int> progreso { get; set; }
        public string incidenc { get; set; }
        public System.DateTime fechaLim { get; set; }
        public string nombreP { get; set; }
        public bool finalizado { get; set; }
        public int trabajador { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
